name: 🚀 Direct Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Fetch Code
        uses: actions/checkout@v4

      - name: 📂 Push to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_42188617
          password: "UxktYgEc9HH"
          server-dir: /htdocs/
